adds spherical brush
joeylmaalouf/SoftSysViolentViolets pull request #26
Opened 2017-04-24 18:09 UTC by jsutker

2017-04-29 18:35 UTC, jovanduy requested changes
Currently, this doesn't compile. I tried messing with some of the places I commented on to get it to compile, but there was no cursor-reshape functionality.

2017-04-29 18:35 UTC, jovanduy commented on src/cursor.cpp
>    return size;
should this return `radius` (not `size`)?

2017-04-29 18:35 UTC, jovanduy commented on src/main.cpp
> +      cursor->setShape(1);
in your comment for get/set shape, you note that the cursor shape options are 0 and 1, but here it seems like they are 1 and 2?

2017-04-29 18:35 UTC, jovanduy commented on src/main.cpp
> +      cursor->setShape(1);
please add these commands to the help list (either under "other" or change "move cursor" to "cursor commands" and put them there

2017-05-01 01:45 UTC, jsutker commented on src/cursor.cpp
>    return size;
there were a few discrepancies, whoops. fixed now

2017-05-01 01:46 UTC, jsutker commented on src/main.cpp
> +      cursor->setShape(1);
the shape values were off by 1 for the keys and the encoded shapes, I changed where that shows up to make it more clear

2017-05-01 03:25 UTC, jovanduy commented
Awesome, it compiles now! 👍 However, maybe I'm missing something, but everything is still just a cube. When I toggle between 1 and 2 (and when I try placing in both modes) nothing changes... Maybe it's just an issue with my computer, but it also didn't work on my Ubuntu VM.

2017-05-02 13:20 UTC, jovanduy approved these changes

2017-05-02 13:29 UTC, merged